@istest private class testgrzopportunitymyselfcontact
{
    /*
@istest static void testmethod1()
{
    List<Account> ac=new List<Account>();
    Account a1=new Account(Name='TPA');
    ac.add(a1);
    insert ac;
    List<Contact> co=new List<Contact>();
    Contact c1=new Contact(Lastname='Pathak');
    c1.AccountId=a1.id;
    co.add(c1);
    Contact c2=new Contact(Lastname='Grazitti');
    c2.AccountId=a1.id;
    co.add(c2);
    insert co;
    List<Opportunity> op=new List<Opportunity>();
    Opportunity op1=new Opportunity();
    op1.name='First come first serve';
    op1.accountid=a1.id;
    op1.contactid=c1.id;
    op1.closedate=date.parse('12/11/2019');
    op1.Amount=5000;
    op1.StageName='Prospecting';
    op.add(op1);
    Opportunity op3=new Opportunity();
    op3.name='First come';
    op3.accountid=a1.id;
    op3.contactid=c1.id;
    op3.closedate=date.parse('12/11/2019');
    op3.Amount=5000;
    op3.StageName='Prospecting';
    op.add(op3);
    insert op;
    op1.Amount=6000;
    update op1;
    List<Opportunity> o=new List<Opportunity>();
    Opportunity op2=new Opportunity();
    op2.Name='Last come last serve';
    op2.accountid=a1.id;
    //op2.contactid=null;
    op2.closedate=date.parse('12/11/2019'); 
    op2.Amount=5000;
    op2.StageName='Prospecting';
    o.add(op2);
    insert o;
    List<Opportunity> opp=[select id from opportunity];
    delete opp;
    List<Contact> co1=[select id from contact];
    delete co1;
}
*/}